import {Injectable} from '@angular/core';

import * as qg from './graph';

@Injectable()
export class DataService {
  getGraphs() {
    return [graphOne(), graphTwo(), graphThree()];
  }
}

function graphOne(n = 100) {
  const g = new qg.Graph<any, any, any>({});
  for (let i = 1; i <= n; i++) {
    g.setNode(String(i), {});
  }
  for (let i = 1; i <= n; i++) {
    for (let m = 2; i * m <= n; m++) {
      g.setEdge([i, i * m], {});
    }
  }
  return g;
}

function graphTwo() {
  const g = new qg.Graph<any, any, any>({});
  two.nodes.forEach(d => {
    g.setNode(d.id, {id: d.id, Xgroup: d.group});
  });
  two.links.forEach(d => {
    g.setEdge([d.n0, d.n1], {Xvalue: d.value});
  });
  return g;
}

function graphThree() {
  const g = new qg.Graph<any, any, any>({});
  three.forEach(d => {
    g.setNode(d[0], {});
    g.setNode(d[1], {});
    g.setEdge([d[0], d[1]], {});
  });
  return g;
}

const two = {
  nodes: [
    {id: 'Myriel', group: 1},
    {id: 'Napoleon', group: 1},
    {id: 'Mlle.Baptistine', group: 1},
    {id: 'Mme.Magloire', group: 1},
    {id: 'CountessdeLo', group: 1},
    {id: 'Geborand', group: 1},
    {id: 'Champtercier', group: 1},
    {id: 'Cravatte', group: 1},
    {id: 'Count', group: 1},
    {id: 'OldMan', group: 1},
    {id: 'Labarre', group: 2},
    {id: 'Valjean', group: 2},
    {id: 'Marguerite', group: 3},
    {id: 'Mme.deR', group: 2},
    {id: 'Isabeau', group: 2},
    {id: 'Gervais', group: 2},
    {id: 'Tholomyes', group: 3},
    {id: 'Listolier', group: 3},
    {id: 'Fameuil', group: 3},
    {id: 'Blacheville', group: 3},
    {id: 'Favourite', group: 3},
    {id: 'Dahlia', group: 3},
    {id: 'Zephine', group: 3},
    {id: 'Fantine', group: 3},
    {id: 'Mme.Thenardier', group: 4},
    {id: 'Thenardier', group: 4},
    {id: 'Cosette', group: 5},
    {id: 'Javert', group: 4},
    {id: 'Fauchelevent', group: 0},
    {id: 'Bamatabois', group: 2},
    {id: 'Perpetue', group: 3},
    {id: 'Simplice', group: 2},
    {id: 'Scaufflaire', group: 2},
    {id: 'Woman1', group: 2},
    {id: 'Judge', group: 2},
    {id: 'Champmathieu', group: 2},
    {id: 'Brevet', group: 2},
    {id: 'Chenildieu', group: 2},
    {id: 'Cochepaille', group: 2},
    {id: 'Pontmercy', group: 4},
    {id: 'Boulatruelle', group: 6},
    {id: 'Eponine', group: 4},
    {id: 'Anzelma', group: 4},
    {id: 'Woman2', group: 5},
    {id: 'MotherInnocent', group: 0},
    {id: 'Gribier', group: 0},
    {id: 'Jondrette', group: 7},
    {id: 'Mme.Burgon', group: 7},
    {id: 'Gavroche', group: 8},
    {id: 'Gillenormand', group: 5},
    {id: 'Magnon', group: 5},
    {id: 'Mlle.Gillenormand', group: 5},
    {id: 'Mme.Pontmercy', group: 5},
    {id: 'Mlle.Vaubois', group: 5},
    {id: 'Lt.Gillenormand', group: 5},
    {id: 'Marius', group: 8},
    {id: 'BaronessT', group: 5},
    {id: 'Mabeuf', group: 8},
    {id: 'Enjolras', group: 8},
    {id: 'Combeferre', group: 8},
    {id: 'Prouvaire', group: 8},
    {id: 'Feuilly', group: 8},
    {id: 'Courfeyrac', group: 8},
    {id: 'Bahorel', group: 8},
    {id: 'Bossuet', group: 8},
    {id: 'Joly', group: 8},
    {id: 'Grantaire', group: 8},
    {id: 'MotherPlutarch', group: 9},
    {id: 'Gueulemer', group: 4},
    {id: 'Babet', group: 4},
    {id: 'Claquesous', group: 4},
    {id: 'Montparnasse', group: 4},
    {id: 'Toussaint', group: 5},
    {id: 'Child1', group: 10},
    {id: 'Child2', group: 10},
    {id: 'Brujon', group: 4},
    {id: 'Mme.Hucheloup', group: 8}
  ],
  links: [
    {n0: 'Napoleon', n1: 'Myriel', value: 1},
    {n0: 'Mlle.Baptistine', n1: 'Myriel', value: 8},
    {n0: 'Mme.Magloire', n1: 'Myriel', value: 10},
    {n0: 'Mme.Magloire', n1: 'Mlle.Baptistine', value: 6},
    {n0: 'CountessdeLo', n1: 'Myriel', value: 1},
    {n0: 'Geborand', n1: 'Myriel', value: 1},
    {n0: 'Champtercier', n1: 'Myriel', value: 1},
    {n0: 'Cravatte', n1: 'Myriel', value: 1},
    {n0: 'Count', n1: 'Myriel', value: 2},
    {n0: 'OldMan', n1: 'Myriel', value: 1},
    {n0: 'Valjean', n1: 'Labarre', value: 1},
    {n0: 'Valjean', n1: 'Mme.Magloire', value: 3},
    {n0: 'Valjean', n1: 'Mlle.Baptistine', value: 3},
    {n0: 'Valjean', n1: 'Myriel', value: 5},
    {n0: 'Marguerite', n1: 'Valjean', value: 1},
    {n0: 'Mme.deR', n1: 'Valjean', value: 1},
    {n0: 'Isabeau', n1: 'Valjean', value: 1},
    {n0: 'Gervais', n1: 'Valjean', value: 1},
    {n0: 'Listolier', n1: 'Tholomyes', value: 4},
    {n0: 'Fameuil', n1: 'Tholomyes', value: 4},
    {n0: 'Fameuil', n1: 'Listolier', value: 4},
    {n0: 'Blacheville', n1: 'Tholomyes', value: 4},
    {n0: 'Blacheville', n1: 'Listolier', value: 4},
    {n0: 'Blacheville', n1: 'Fameuil', value: 4},
    {n0: 'Favourite', n1: 'Tholomyes', value: 3},
    {n0: 'Favourite', n1: 'Listolier', value: 3},
    {n0: 'Favourite', n1: 'Fameuil', value: 3},
    {n0: 'Favourite', n1: 'Blacheville', value: 4},
    {n0: 'Dahlia', n1: 'Tholomyes', value: 3},
    {n0: 'Dahlia', n1: 'Listolier', value: 3},
    {n0: 'Dahlia', n1: 'Fameuil', value: 3},
    {n0: 'Dahlia', n1: 'Blacheville', value: 3},
    {n0: 'Dahlia', n1: 'Favourite', value: 5},
    {n0: 'Zephine', n1: 'Tholomyes', value: 3},
    {n0: 'Zephine', n1: 'Listolier', value: 3},
    {n0: 'Zephine', n1: 'Fameuil', value: 3},
    {n0: 'Zephine', n1: 'Blacheville', value: 3},
    {n0: 'Zephine', n1: 'Favourite', value: 4},
    {n0: 'Zephine', n1: 'Dahlia', value: 4},
    {n0: 'Fantine', n1: 'Tholomyes', value: 3},
    {n0: 'Fantine', n1: 'Listolier', value: 3},
    {n0: 'Fantine', n1: 'Fameuil', value: 3},
    {n0: 'Fantine', n1: 'Blacheville', value: 3},
    {n0: 'Fantine', n1: 'Favourite', value: 4},
    {n0: 'Fantine', n1: 'Dahlia', value: 4},
    {n0: 'Fantine', n1: 'Zephine', value: 4},
    {n0: 'Fantine', n1: 'Marguerite', value: 2},
    {n0: 'Fantine', n1: 'Valjean', value: 9},
    {n0: 'Mme.Thenardier', n1: 'Fantine', value: 2},
    {n0: 'Mme.Thenardier', n1: 'Valjean', value: 7},
    {n0: 'Thenardier', n1: 'Mme.Thenardier', value: 13},
    {n0: 'Thenardier', n1: 'Fantine', value: 1},
    {n0: 'Thenardier', n1: 'Valjean', value: 12},
    {n0: 'Cosette', n1: 'Mme.Thenardier', value: 4},
    {n0: 'Cosette', n1: 'Valjean', value: 31},
    {n0: 'Cosette', n1: 'Tholomyes', value: 1},
    {n0: 'Cosette', n1: 'Thenardier', value: 1},
    {n0: 'Javert', n1: 'Valjean', value: 17},
    {n0: 'Javert', n1: 'Fantine', value: 5},
    {n0: 'Javert', n1: 'Thenardier', value: 5},
    {n0: 'Javert', n1: 'Mme.Thenardier', value: 1},
    {n0: 'Javert', n1: 'Cosette', value: 1},
    {n0: 'Fauchelevent', n1: 'Valjean', value: 8},
    {n0: 'Fauchelevent', n1: 'Javert', value: 1},
    {n0: 'Bamatabois', n1: 'Fantine', value: 1},
    {n0: 'Bamatabois', n1: 'Javert', value: 1},
    {n0: 'Bamatabois', n1: 'Valjean', value: 2},
    {n0: 'Perpetue', n1: 'Fantine', value: 1},
    {n0: 'Simplice', n1: 'Perpetue', value: 2},
    {n0: 'Simplice', n1: 'Valjean', value: 3},
    {n0: 'Simplice', n1: 'Fantine', value: 2},
    {n0: 'Simplice', n1: 'Javert', value: 1},
    {n0: 'Scaufflaire', n1: 'Valjean', value: 1},
    {n0: 'Woman1', n1: 'Valjean', value: 2},
    {n0: 'Woman1', n1: 'Javert', value: 1},
    {n0: 'Judge', n1: 'Valjean', value: 3},
    {n0: 'Judge', n1: 'Bamatabois', value: 2},
    {n0: 'Champmathieu', n1: 'Valjean', value: 3},
    {n0: 'Champmathieu', n1: 'Judge', value: 3},
    {n0: 'Champmathieu', n1: 'Bamatabois', value: 2},
    {n0: 'Brevet', n1: 'Judge', value: 2},
    {n0: 'Brevet', n1: 'Champmathieu', value: 2},
    {n0: 'Brevet', n1: 'Valjean', value: 2},
    {n0: 'Brevet', n1: 'Bamatabois', value: 1},
    {n0: 'Chenildieu', n1: 'Judge', value: 2},
    {n0: 'Chenildieu', n1: 'Champmathieu', value: 2},
    {n0: 'Chenildieu', n1: 'Brevet', value: 2},
    {n0: 'Chenildieu', n1: 'Valjean', value: 2},
    {n0: 'Chenildieu', n1: 'Bamatabois', value: 1},
    {n0: 'Cochepaille', n1: 'Judge', value: 2},
    {n0: 'Cochepaille', n1: 'Champmathieu', value: 2},
    {n0: 'Cochepaille', n1: 'Brevet', value: 2},
    {n0: 'Cochepaille', n1: 'Chenildieu', value: 2},
    {n0: 'Cochepaille', n1: 'Valjean', value: 2},
    {n0: 'Cochepaille', n1: 'Bamatabois', value: 1},
    {n0: 'Pontmercy', n1: 'Thenardier', value: 1},
    {n0: 'Boulatruelle', n1: 'Thenardier', value: 1},
    {n0: 'Eponine', n1: 'Mme.Thenardier', value: 2},
    {n0: 'Eponine', n1: 'Thenardier', value: 3},
    {n0: 'Anzelma', n1: 'Eponine', value: 2},
    {n0: 'Anzelma', n1: 'Thenardier', value: 2},
    {n0: 'Anzelma', n1: 'Mme.Thenardier', value: 1},
    {n0: 'Woman2', n1: 'Valjean', value: 3},
    {n0: 'Woman2', n1: 'Cosette', value: 1},
    {n0: 'Woman2', n1: 'Javert', value: 1},
    {n0: 'MotherInnocent', n1: 'Fauchelevent', value: 3},
    {n0: 'MotherInnocent', n1: 'Valjean', value: 1},
    {n0: 'Gribier', n1: 'Fauchelevent', value: 2},
    {n0: 'Mme.Burgon', n1: 'Jondrette', value: 1},
    {n0: 'Gavroche', n1: 'Mme.Burgon', value: 2},
    {n0: 'Gavroche', n1: 'Thenardier', value: 1},
    {n0: 'Gavroche', n1: 'Javert', value: 1},
    {n0: 'Gavroche', n1: 'Valjean', value: 1},
    {n0: 'Gillenormand', n1: 'Cosette', value: 3},
    {n0: 'Gillenormand', n1: 'Valjean', value: 2},
    {n0: 'Magnon', n1: 'Gillenormand', value: 1},
    {n0: 'Magnon', n1: 'Mme.Thenardier', value: 1},
    {n0: 'Mlle.Gillenormand', n1: 'Gillenormand', value: 9},
    {n0: 'Mlle.Gillenormand', n1: 'Cosette', value: 2},
    {n0: 'Mlle.Gillenormand', n1: 'Valjean', value: 2},
    {n0: 'Mme.Pontmercy', n1: 'Mlle.Gillenormand', value: 1},
    {n0: 'Mme.Pontmercy', n1: 'Pontmercy', value: 1},
    {n0: 'Mlle.Vaubois', n1: 'Mlle.Gillenormand', value: 1},
    {n0: 'Lt.Gillenormand', n1: 'Mlle.Gillenormand', value: 2},
    {n0: 'Lt.Gillenormand', n1: 'Gillenormand', value: 1},
    {n0: 'Lt.Gillenormand', n1: 'Cosette', value: 1},
    {n0: 'Marius', n1: 'Mlle.Gillenormand', value: 6},
    {n0: 'Marius', n1: 'Gillenormand', value: 12},
    {n0: 'Marius', n1: 'Pontmercy', value: 1},
    {n0: 'Marius', n1: 'Lt.Gillenormand', value: 1},
    {n0: 'Marius', n1: 'Cosette', value: 21},
    {n0: 'Marius', n1: 'Valjean', value: 19},
    {n0: 'Marius', n1: 'Tholomyes', value: 1},
    {n0: 'Marius', n1: 'Thenardier', value: 2},
    {n0: 'Marius', n1: 'Eponine', value: 5},
    {n0: 'Marius', n1: 'Gavroche', value: 4},
    {n0: 'BaronessT', n1: 'Gillenormand', value: 1},
    {n0: 'BaronessT', n1: 'Marius', value: 1},
    {n0: 'Mabeuf', n1: 'Marius', value: 1},
    {n0: 'Mabeuf', n1: 'Eponine', value: 1},
    {n0: 'Mabeuf', n1: 'Gavroche', value: 1},
    {n0: 'Enjolras', n1: 'Marius', value: 7},
    {n0: 'Enjolras', n1: 'Gavroche', value: 7},
    {n0: 'Enjolras', n1: 'Javert', value: 6},
    {n0: 'Enjolras', n1: 'Mabeuf', value: 1},
    {n0: 'Enjolras', n1: 'Valjean', value: 4},
    {n0: 'Combeferre', n1: 'Enjolras', value: 15},
    {n0: 'Combeferre', n1: 'Marius', value: 5},
    {n0: 'Combeferre', n1: 'Gavroche', value: 6},
    {n0: 'Combeferre', n1: 'Mabeuf', value: 2},
    {n0: 'Prouvaire', n1: 'Gavroche', value: 1},
    {n0: 'Prouvaire', n1: 'Enjolras', value: 4},
    {n0: 'Prouvaire', n1: 'Combeferre', value: 2},
    {n0: 'Feuilly', n1: 'Gavroche', value: 2},
    {n0: 'Feuilly', n1: 'Enjolras', value: 6},
    {n0: 'Feuilly', n1: 'Prouvaire', value: 2},
    {n0: 'Feuilly', n1: 'Combeferre', value: 5},
    {n0: 'Feuilly', n1: 'Mabeuf', value: 1},
    {n0: 'Feuilly', n1: 'Marius', value: 1},
    {n0: 'Courfeyrac', n1: 'Marius', value: 9},
    {n0: 'Courfeyrac', n1: 'Enjolras', value: 17},
    {n0: 'Courfeyrac', n1: 'Combeferre', value: 13},
    {n0: 'Courfeyrac', n1: 'Gavroche', value: 7},
    {n0: 'Courfeyrac', n1: 'Mabeuf', value: 2},
    {n0: 'Courfeyrac', n1: 'Eponine', value: 1},
    {n0: 'Courfeyrac', n1: 'Feuilly', value: 6},
    {n0: 'Courfeyrac', n1: 'Prouvaire', value: 3},
    {n0: 'Bahorel', n1: 'Combeferre', value: 5},
    {n0: 'Bahorel', n1: 'Gavroche', value: 5},
    {n0: 'Bahorel', n1: 'Courfeyrac', value: 6},
    {n0: 'Bahorel', n1: 'Mabeuf', value: 2},
    {n0: 'Bahorel', n1: 'Enjolras', value: 4},
    {n0: 'Bahorel', n1: 'Feuilly', value: 3},
    {n0: 'Bahorel', n1: 'Prouvaire', value: 2},
    {n0: 'Bahorel', n1: 'Marius', value: 1},
    {n0: 'Bossuet', n1: 'Marius', value: 5},
    {n0: 'Bossuet', n1: 'Courfeyrac', value: 12},
    {n0: 'Bossuet', n1: 'Gavroche', value: 5},
    {n0: 'Bossuet', n1: 'Bahorel', value: 4},
    {n0: 'Bossuet', n1: 'Enjolras', value: 10},
    {n0: 'Bossuet', n1: 'Feuilly', value: 6},
    {n0: 'Bossuet', n1: 'Prouvaire', value: 2},
    {n0: 'Bossuet', n1: 'Combeferre', value: 9},
    {n0: 'Bossuet', n1: 'Mabeuf', value: 1},
    {n0: 'Bossuet', n1: 'Valjean', value: 1},
    {n0: 'Joly', n1: 'Bahorel', value: 5},
    {n0: 'Joly', n1: 'Bossuet', value: 7},
    {n0: 'Joly', n1: 'Gavroche', value: 3},
    {n0: 'Joly', n1: 'Courfeyrac', value: 5},
    {n0: 'Joly', n1: 'Enjolras', value: 5},
    {n0: 'Joly', n1: 'Feuilly', value: 5},
    {n0: 'Joly', n1: 'Prouvaire', value: 2},
    {n0: 'Joly', n1: 'Combeferre', value: 5},
    {n0: 'Joly', n1: 'Mabeuf', value: 1},
    {n0: 'Joly', n1: 'Marius', value: 2},
    {n0: 'Grantaire', n1: 'Bossuet', value: 3},
    {n0: 'Grantaire', n1: 'Enjolras', value: 3},
    {n0: 'Grantaire', n1: 'Combeferre', value: 1},
    {n0: 'Grantaire', n1: 'Courfeyrac', value: 2},
    {n0: 'Grantaire', n1: 'Joly', value: 2},
    {n0: 'Grantaire', n1: 'Gavroche', value: 1},
    {n0: 'Grantaire', n1: 'Bahorel', value: 1},
    {n0: 'Grantaire', n1: 'Feuilly', value: 1},
    {n0: 'Grantaire', n1: 'Prouvaire', value: 1},
    {n0: 'MotherPlutarch', n1: 'Mabeuf', value: 3},
    {n0: 'Gueulemer', n1: 'Thenardier', value: 5},
    {n0: 'Gueulemer', n1: 'Valjean', value: 1},
    {n0: 'Gueulemer', n1: 'Mme.Thenardier', value: 1},
    {n0: 'Gueulemer', n1: 'Javert', value: 1},
    {n0: 'Gueulemer', n1: 'Gavroche', value: 1},
    {n0: 'Gueulemer', n1: 'Eponine', value: 1},
    {n0: 'Babet', n1: 'Thenardier', value: 6},
    {n0: 'Babet', n1: 'Gueulemer', value: 6},
    {n0: 'Babet', n1: 'Valjean', value: 1},
    {n0: 'Babet', n1: 'Mme.Thenardier', value: 1},
    {n0: 'Babet', n1: 'Javert', value: 2},
    {n0: 'Babet', n1: 'Gavroche', value: 1},
    {n0: 'Babet', n1: 'Eponine', value: 1},
    {n0: 'Claquesous', n1: 'Thenardier', value: 4},
    {n0: 'Claquesous', n1: 'Babet', value: 4},
    {n0: 'Claquesous', n1: 'Gueulemer', value: 4},
    {n0: 'Claquesous', n1: 'Valjean', value: 1},
    {n0: 'Claquesous', n1: 'Mme.Thenardier', value: 1},
    {n0: 'Claquesous', n1: 'Javert', value: 1},
    {n0: 'Claquesous', n1: 'Eponine', value: 1},
    {n0: 'Claquesous', n1: 'Enjolras', value: 1},
    {n0: 'Montparnasse', n1: 'Javert', value: 1},
    {n0: 'Montparnasse', n1: 'Babet', value: 2},
    {n0: 'Montparnasse', n1: 'Gueulemer', value: 2},
    {n0: 'Montparnasse', n1: 'Claquesous', value: 2},
    {n0: 'Montparnasse', n1: 'Valjean', value: 1},
    {n0: 'Montparnasse', n1: 'Gavroche', value: 1},
    {n0: 'Montparnasse', n1: 'Eponine', value: 1},
    {n0: 'Montparnasse', n1: 'Thenardier', value: 1},
    {n0: 'Toussaint', n1: 'Cosette', value: 2},
    {n0: 'Toussaint', n1: 'Javert', value: 1},
    {n0: 'Toussaint', n1: 'Valjean', value: 1},
    {n0: 'Child1', n1: 'Gavroche', value: 2},
    {n0: 'Child2', n1: 'Gavroche', value: 2},
    {n0: 'Child2', n1: 'Child1', value: 3},
    {n0: 'Brujon', n1: 'Babet', value: 3},
    {n0: 'Brujon', n1: 'Gueulemer', value: 3},
    {n0: 'Brujon', n1: 'Thenardier', value: 3},
    {n0: 'Brujon', n1: 'Gavroche', value: 1},
    {n0: 'Brujon', n1: 'Eponine', value: 1},
    {n0: 'Brujon', n1: 'Claquesous', value: 1},
    {n0: 'Brujon', n1: 'Montparnasse', value: 1},
    {n0: 'Mme.Hucheloup', n1: 'Bossuet', value: 1},
    {n0: 'Mme.Hucheloup', n1: 'Joly', value: 1},
    {n0: 'Mme.Hucheloup', n1: 'Grantaire', value: 1},
    {n0: 'Mme.Hucheloup', n1: 'Bahorel', value: 1},
    {n0: 'Mme.Hucheloup', n1: 'Courfeyrac', value: 1},
    {n0: 'Mme.Hucheloup', n1: 'Gavroche', value: 1},
    {n0: 'Mme.Hucheloup', n1: 'Enjolras', value: 1}
  ]
};

const three = [
  ['S8', '9'],
  ['S24', '27'],
  ['S24', '25'],
  ['S1', '10'],
  ['S1', '2'],
  ['S35', '36'],
  ['S35', '43'],
  ['S30', '31'],
  ['S30', '33'],
  ['9', '42'],
  ['9', 'T1'],
  ['25', 'T1'],
  ['25', '26'],
  ['27', 'T24'],
  ['2', '3'],
  ['2', '16'],
  ['2', '17'],
  ['2', 'T1'],
  ['2', '18'],
  ['10', '11'],
  ['10', '14'],
  ['10', 'T1'],
  ['10', '13'],
  ['10', '12'],
  ['31', 'T1'],
  ['31', '32'],
  ['33', 'T30'],
  ['33', '34'],
  ['42', '4'],
  ['26', '4'],
  ['3', '4'],
  ['16', '15'],
  ['17', '19'],
  ['18', '29'],
  ['11', '4'],
  ['14', '15'],
  ['37', '39'],
  ['37', '41'],
  ['37', '38'],
  ['37', '40'],
  ['13', '19'],
  ['12', '29'],
  ['43', '38'],
  ['43', '40'],
  ['36', '19'],
  ['32', '23'],
  ['34', '29'],
  ['39', '15'],
  ['41', '29'],
  ['38', '4'],
  ['40', '19'],
  ['4', '5'],
  ['19', '21'],
  ['19', '20'],
  ['19', '28'],
  ['5', '6'],
  ['5', 'T35'],
  ['5', '23'],
  ['21', '22'],
  ['20', '15'],
  ['28', '29'],
  ['6', '7'],
  ['15', 'T1'],
  ['22', '23'],
  ['22', 'T35'],
  ['29', 'T30'],
  ['7', 'T8'],
  ['23', 'T24'],
  ['23', 'T1']
];

/*
node [fontsize=24, shape = plaintext];
1972',1976',1978',1980',1982',1984',1986',1988
-> 1990',future;
node [fontsize=20, shape = box];
{ rank = same; 1976 Mashey Bourne; }
{ rank = same; 1978 Formshell csh; }
{ rank = same; 1980 esh vsh; }
{ rank = same; 1982 ksh "System-V"; }
{ rank = same; 1984 v9sh tcsh; }
{ rank = same; 1986 "ksh-i"; }
{ rank = same; 1988 KornShell Perl rc; }
{ rank = same; 1990 tcl Bash; }
{ rank = same; "future" POSIX "ksh-POSIX"; }
Thompson',{Mashey Bourne csh}; csh',tcsh; Bourne',{ksh esh vsh "System-V" v9sh}; v9sh',rc;
{Bourne "ksh-i" KornShell}',Bash; {esh vsh Formshell csh}',ksh;
{KornShell "System-V"}',POSIX;
ksh',"ksh-i"',KornShell',"ksh-POSIX"; Bourne',Formshell;

edge [style=invis];
1984',v9sh',tcsh ; 1988',rc',KornShell; Formshell',csh; KornShell',Perl;
*/
