export const enum Syntax {
  AbstractKeyword,
  Ampersand2Token,
  AmpersandEqualsToken,
  AmpersandToken,
  AnyKeyword,
  AsExpression,
  AsKeyword,
  AssertsKeyword,
  Asterisk2EqualsToken,
  Asterisk2Token,
  AsteriskEqualsToken,
  AsteriskToken,
  AsyncKeyword,
  AtToken,
  AwaitExpression,
  AwaitKeyword,
  BacktickToken,
  Bar2Token,
  BarEqualsToken,
  BarToken,
  BigIntKeyword,
  BigIntLiteral,
  BinaryExpression,
  BindingElement,
  Block,
  BooleanKeyword,
  BreakKeyword,
  BreakStatement,
  Bundle,
  CallExpression,
  CallSignature,
  CaretEqualsToken,
  CaretToken,
  CaseBlock,
  CaseClause,
  CaseKeyword,
  CatchClause,
  CatchKeyword,
  ClassDeclaration,
  ClassExpression,
  ClassKeyword,
  CloseBraceToken,
  CloseBracketToken,
  CloseParenToken,
  ColonToken,
  CommaListExpression,
  CommaToken,
  ComputedPropertyName,
  ConditionalExpression,
  ConditionalType,
  ConflictMarkerTrivia,
  ConstKeyword,
  Constructor,
  ConstructorKeyword,
  ConstructorType,
  ConstructSignature,
  ContinueKeyword,
  ContinueStatement,
  Count,
  DebuggerKeyword,
  DebuggerStatement,
  DeclareKeyword,
  Decorator,
  DefaultClause,
  DefaultKeyword,
  DeleteExpression,
  DeleteKeyword,
  DoKeyword,
  DoStatement,
  Dot3Token,
  DotToken,
  ElementAccessExpression,
  ElseKeyword,
  EmptyStatement,
  EndOfDeclarationMarker,
  EndOfFileToken,
  EnumDeclaration,
  EnumKeyword,
  EnumMember,
  Equals2Token,
  Equals3Token,
  EqualsGreaterThanToken,
  EqualsToken,
  ExclamationEquals2Token,
  ExclamationEqualsToken,
  ExclamationToken,
  ExportAssignment,
  ExportDeclaration,
  ExportKeyword,
  ExportSpecifier,
  ExpressionStatement,
  ExpressionWithTypeArguments,
  ExtendsKeyword,
  ExternalModuleReference,
  FalseKeyword,
  FinallyKeyword,
  FirstAssignment = EqualsToken,
  FirstBinaryOperator = LessThanToken,
  FirstCompoundAssignment = PlusEqualsToken,
  FirstContextualKeyword = AbstractKeyword,
  FirstFutureReservedWord = ImplementsKeyword,
  FirstJSDocNode = JSDocTypeExpression,
  FirstJSDocTagNode = JSDocTag,
  FirstKeyword = BreakKeyword,
  FirstLiteralToken = NumericLiteral,
  FirstNode = QualifiedName,
  FirstPunctuation = OpenBraceToken,
  FirstReservedWord = BreakKeyword,
  FirstStatement = VariableStatement,
  FirstTemplateToken = NoSubstitutionLiteral,
  FirstToken = Unknown,
  FirstTriviaToken = SingleLineCommentTrivia,
  FirstTypeNode = TypePredicate,
  ForInStatement,
  ForKeyword,
  ForOfStatement,
  ForStatement,
  FromKeyword,
  FunctionDeclaration,
  FunctionExpression,
  FunctionKeyword,
  FunctionType,
  GetAccessor,
  GetKeyword,
  GlobalKeyword,
  GreaterThan2EqualsToken,
  GreaterThan2Token,
  GreaterThan3EqualsToken,
  GreaterThan3Token,
  GreaterThanEqualsToken,
  GreaterThanToken,
  HeritageClause,
  Identifier,
  IfKeyword,
  IfStatement,
  ImplementsKeyword,
  ImportClause,
  ImportDeclaration,
  ImportEqualsDeclaration,
  ImportKeyword,
  ImportSpecifier,
  ImportType,
  IndexedAccessType,
  IndexSignature,
  InferKeyword,
  InferType,
  InKeyword,
  InputFiles,
  InstanceOfKeyword,
  InterfaceDeclaration,
  InterfaceKeyword,
  IntersectionType,
  IsKeyword,
  JSDocAllType,
  JSDocAugmentsTag,
  JSDocAuthorTag,
  JSDocCallbackTag,
  JSDocClassTag,
  JSDocComment,
  JSDocEnumTag,
  JSDocFunctionType,
  JSDocImplementsTag,
  JSDocNamepathType,
  JSDocNonNullableType,
  JSDocNullableType,
  JSDocOptionalType,
  JSDocParameterTag,
  JSDocPrivateTag,
  JSDocPropertyTag,
  JSDocProtectedTag,
  JSDocPublicTag,
  JSDocReadonlyTag,
  JSDocReturnTag,
  JSDocSignature,
  JSDocTag,
  JSDocTemplateTag,
  JSDocThisTag,
  JSDocTypedefTag,
  JSDocTypeExpression,
  JSDocTypeLiteral,
  JSDocTypeTag,
  JSDocUnknownType,
  JSDocVariadicType,
  JsxAttribute,
  JsxAttributes,
  JsxClosingElement,
  JsxClosingFragment,
  JsxElement,
  JsxExpression,
  JsxFragment,
  JsxOpeningElement,
  JsxOpeningFragment,
  JsxSelfClosingElement,
  JsxSpreadAttribute,
  JsxText,
  JsxTextAllWhiteSpaces,
  KeyOfKeyword,
  LabeledStatement,
  LastAssignment = CaretEqualsToken,
  LastBinaryOperator = CaretEqualsToken,
  LastCompoundAssignment = CaretEqualsToken,
  LastContextualKeyword = OfKeyword,
  LastFutureReservedWord = YieldKeyword,
  LastJSDocNode = JSDocPropertyTag,
  LastJSDocTagNode = JSDocPropertyTag,
  LastKeyword = OfKeyword,
  LastLiteralToken = NoSubstitutionLiteral,
  LastPunctuation = CaretEqualsToken,
  LastReservedWord = WithKeyword,
  LastStatement = DebuggerStatement,
  LastTemplateToken = TemplateTail,
  LastToken = LastKeyword,
  LastTriviaToken = ConflictMarkerTrivia,
  LastTypeNode = ImportType,
  LessThan2EqualsToken,
  LessThan2Token,
  LessThanEqualsToken,
  LessThanSlashToken,
  LessThanToken,
  LetKeyword,
  LiteralType,
  MappedType,
  MergeDeclarationMarker,
  MetaProperty,
  MethodDeclaration,
  MethodSignature,
  Minus2Token,
  MinusEqualsToken,
  MinusToken,
  MissingDeclaration,
  ModuleBlock,
  ModuleDeclaration,
  ModuleKeyword,
  MultiLineCommentTrivia,
  NamedExports,
  NamedImports,
  NamedTupleMember,
  NamespaceExport,
  NamespaceExportDeclaration,
  NamespaceImport,
  NamespaceKeyword,
  NeverKeyword,
  NewExpression,
  NewKeyword,
  NewLineTrivia,
  NonNullExpression,
  NoSubstitutionLiteral,
  NotEmittedStatement,
  NullKeyword,
  NumberKeyword,
  NumericLiteral,
  ObjectBindingPattern,
  ObjectKeyword,
  ObjectLiteralExpression,
  OfKeyword, // LastKeyword and LastToken and LastContextualKeyword
  OmittedExpression,
  OpenBraceToken,
  OpenBracketToken,
  OpenParenToken,
  OptionalType,
  PackageKeyword,
  Parameter,
  ParenthesizedExpression,
  ParenthesizedType,
  PartiallyEmittedExpression,
  PercentEqualsToken,
  PercentToken,
  Plus2Token,
  PlusEqualsToken,
  PlusToken,
  PostfixUnaryExpression,
  PrefixUnaryExpression,
  PrivateIdentifier,
  PrivateKeyword,
  PropertyAccessExpression,
  PropertyAssignment,
  PropertyDeclaration,
  PropertySignature,
  ProtectedKeyword,
  PublicKeyword,
  QualifiedName,
  Question2Token,
  QuestionDotToken,
  QuestionToken,
  ReadonlyKeyword,
  RegexLiteral,
  RequireKeyword,
  RestType,
  ReturnKeyword,
  ReturnStatement,
  SemicolonClassElement,
  SemicolonToken,
  SetAccessor,
  SetKeyword,
  ShebangTrivia,
  ShorthandPropertyAssignment,
  SingleLineCommentTrivia,
  SlashEqualsToken,
  SlashToken,
  SourceFile,
  SpreadAssignment,
  SpreadElement,
  StaticKeyword,
  StringKeyword,
  StringLiteral,
  SuperKeyword,
  SwitchKeyword,
  SwitchStatement,
  SymbolKeyword,
  SyntaxList,
  SyntheticExpression,
  SyntheticReferenceExpression,
  TaggedTemplateExpression,
  TemplateExpression,
  TemplateHead,
  TemplateMiddle,
  TemplateSpan,
  TemplateTail,
  ThisKeyword,
  ThisType,
  ThrowKeyword,
  ThrowStatement,
  TildeToken,
  TrueKeyword,
  TryKeyword,
  TryStatement,
  TupleType,
  TypeAliasDeclaration,
  TypeAssertionExpression,
  TypeKeyword,
  TypeLiteral,
  TypeOfExpression,
  TypeOfKeyword,
  TypeOperator,
  TypeParameter,
  TypePredicate,
  TypeQuery,
  TypeReference,
  UndefinedKeyword,
  UnionType,
  UniqueKeyword,
  Unknown,
  UnknownKeyword,
  UnparsedInternalText,
  UnparsedPrepend,
  UnparsedPrologue,
  UnparsedSource,
  UnparsedSyntheticReference,
  UnparsedText,
  VariableDeclaration,
  VariableDeclarationList,
  VariableStatement,
  VarKeyword,
  VoidExpression,
  VoidKeyword,
  WhileKeyword,
  WhileStatement,
  WhitespaceTrivia,
  WithKeyword,
  WithStatement,
  YieldExpression,
  YieldKeyword,
}


ArrayType,
